### ISSUE TITLE
github action for js google style lint 

### ISSUE THREAD

**Issue by MatoPlus** [team-vibe-labs/blockly-samples#8]

**Comment by d-projects** [comment]
To lint changes in the `blockly-samples/plugins` directory, you have to run `npm run lint:fix`. Note that linting cannot be currently done in the `blockly-samples/examples` directory.

**Comment by d-projects** [comment]
To lint changes in the `blockly-samples/plugins` directory, you have to run `npm run lint:fix`. Note that linting cannot be currently done in the `blockly-samples/examples` directory.
